Update  config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -6,6 +6,9 @@ jobs:
         environment:
           RAILS_ENV: test
           DB_HOST: 127.0.0.1
+          BUNDLE_JOBS: 1
+          BUNDLE_RETRY: 1
+          BUNDLE_PATH: vendor/bundle
           CIRCLE_CI: 'true'
           CACHE_VERSION: 'v1'
       - image: circleci/mysql:5.7.28
@@ -13,8 +16,115 @@ jobs:
           MYSQL_ALLOW_EMPTY_PASSWORD: "true"
           MYSQL_ROOT_HOST: "%"
     parallelism: 4
-    commands:
-      - bundle exec rake test
+    steps:
+      - checkout
+      - restore_cache:
+          key: bundle-{{ checksum "Gemfile.lock" }}
+      - run:
+          name: Install bundle
+          command: bin/bundle install --path vendor/bundle
+
+      - save_cache:
+          key: bundle-{{ checksum "Gemfile.lock" }}
+          paths:
+            - vendor/bundle
+      - run:
+          name: Wait for DB
+          command: dockerize -wait tcp://localhost:3306 -timeout 1m
+
+      - run:
+          name: Build the Settings YML files
+          command: |-
+            mkdir -p config && echo '
+              api_product_codes:
+                {100: "evucc256sslcom", 101: "ucc256sslcom", 102: "ev256sslcom",
+                 103: "ov256sslcom", 104: "dv256sslcom", 105: "wc256sslcom", 106: "basic256sslcom",
+                 107: "premium256sslcom",
+                 204: "evucc256sslcom", 202: "ucc256sslcom", 203: "ev256sslcom",
+                 200: "basic256sslcom", 201: "wc256sslcom", 300: "personalbasic256sslcom",
+                 301: "personalpro256sslcom", 302: "personalbusiness256sslcom", 303: "personalenterprise256sslcom",
+                 310: "naesbbasic256sslcom", 350: "codesigning256sslcom", 360: "evcodesigning256sslcom"}
+              subca_mapping:
+                dv: {product: "basicssl", label: "<i>SSL</i>.com Basic"}
+                premiumssl: {product: "premiumssl", label: "<i>SSL</i>.com Premium"}
+                ev: {product: "ev", label: "<i>SSL</i>.com Enterprise EV"}
+                ov: {product: "high_assurance", label: "<i>SSL</i>.com High Assurance"}
+                wildcard: {product: "wildcard", label: "Wildcard (Unlimited Subdomains)"}
+                ucc: {product: "ucc", label: "Multi-Domain (SAN/UCC)"}
+                evucc: {product: "evucc", label: "EV Multi-Domain (EV SAN/UCC)"}
+              send_dv_first: true
+            ' > config/settings.yml
+
+      - run:
+          name: Build the Local Environment File on the Fly
+          command: |-
+            mkdir -p config && echo "
+                AWS_ACCESS_KEY_ID: ''
+                AWS_SECRET_ACCESS_KEY: ''
+                S3_BUCKET_NAME: ''
+                S3_AVATAR_BUCKET_NAME: ''
+                AWS_DEFAULT_REGION: ''
+                DUO_INTEGRATION_KEY: '${DUO_INTEGRATION_KEY}'
+                DUO_SECRET_KEY: '${DUO_SECRET_KEY}'
+                DUO_APPLICATION_KEY: '${DUO_APPLICATION_KEY}'
+                DUO_API_HOSTNAME: '${DUO_API_HOSTNAME}'
+                DUO_SYSADMIN_INTEGRATION_KEY: '${DUO_INTEGRATION_KEY}'
+                DUO_SYSADMIN_SECRET_KEY: '${DUO_SECRET_KEY}'
+                DUO_SYSADMIN_APPLICATION_KEY: '${DUO_APPLICATION_KEY}'
+                DUO_SYSADMIN_API_HOSTNAME: '${DUO_API_HOSTNAME}'
+            " > config/local_env.yml
+
+      - run:
+          name: Copy Database config
+          command: cp config/database.yml.example config/database.yml
+
+      - run:
+          name: Copy Settings File
+          command: cp config/client/certassure/settings.yml config/
+
+      - run:
+          name: Create the Test Database, Load the Structure, and Migrate the Latest Migrations
+          command: |-
+            export RAILS_ENV="test"
+            export RACK_ENV="test"
+            bundle exec rake db:create db:structure:load db:migrate --trace
+      - run:
+          name: Run tests
+          # type: shell
+          command: |-
+            TESTFILES=$(circleci tests glob "test/**/*_test.rb" | circleci tests split --split-by=timings)
+            bundle exec rake test \
+              -- ${TESTFILES}
+      # - run:
+      #     name: Run tests
+      #     # type: shell
+      #     command: |-
+      #       TESTFILES=$(circleci tests glob "test/**/*_test.rb" | circleci tests split --split-by=timings)
+      #       bundle exec rake test \
+      #         --no-fail-fast \
+      #         --profile 10 \
+      #         --format RspecJunitFormatter \
+      #         --out test_results/rspec.xml \
+      #         --format progress \
+      #         -- ${TESTFILES}
+      - run:
+          name: Copy Settings File
+          command: cp config/client/certassure/settings.yml config/
+      - run:
+          name: Code Climate Test Coverage
+          command: |
+            ./cc-test-reporter format-coverage -t simplecov -o "coverage/codeclimate.$CIRCLE_NODE_INDEX.json"
+
+      - store_test_results:
+          path: test/reports
+
+      - store_artifacts:
+          path: coverage
+
+      - store_artifacts:
+          path: test/reports
+
+      - run: ./cc-test-reporter after-build -r $CC_TEST_REPORTER_ID -t simplecov --exit-code $? || true
   
   build:
     working_directory: ~/sslcom-rails
@@ -204,35 +314,11 @@ jobs:
           command: |
               bundle exec rails runner 'Rails.application.eager_load!'
 
-  upload-coverage:
-    docker:
-      - image: circleci/ruby:2.6.2-node-browsers
-    environment:
-      # you can add your CodeClimate test report ID here or in CircleCI
-      # settings for environment variables
-      CC_TEST_REPORTER_ID: $CC_TEST_REPORTER_ID
-    working_directory: ~/repo
-
-    steps:
-      # This will restore files from persist_to_workspace step
-      # Thanks to it we will have access to CodeClimate test coverage files from
-      # each parallel job. We need them in order to merge it into one file in next step.
-      - attach_workspace:
-          at: ~/repo
-      - run:
-          name: Install Code Climate Test Reporter
-          command: |
-            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
-            chmod +x ./cc-test-reporter
-      - run: ./cc-test-reporter after-build -t simplecov --exit-code $? || true
-
-
 workflows:
   version: 2
 
   build_and_coverage:
     jobs:
-      - build
-      # - upload-coverage:
-      #     requires:
-      #       - build
+      # - build
+      - test
+
